service: shopfully-backend

provider:
  name: aws
  runtime: nodejs12.x

functions:
  getFlyers:
    handler: handler.getFlyers
    events:
      - http:
          path: /flyers
          method: get

plugins:
  - serverless-offline
